application: legendary-spain
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# making index.html as default page for root
- url: /
  static_files: static/index.html
  upload: static/index.html

# begin any static files request from www folder
- url: /
  static_dir: static